### ISSUE TITLE
UDTs which have a field of type Set<UDT> throw exception 'Unknown type.' in Cassandra\Type\Base.php when running INSERT CQL

### ISSUE THREAD

**Issue by steambao** [duoshuo/php-cassandra#17]
I have a UDT which has a SET of another type of UDT.

Example CQL:

```
CREATE TYPE part (
    name text,
    color text
);
CREATE TYPE car (
    make text,
    model text,
    parts set<frozen<part>>
);
CREATE TABLE IF NOT EXISTS cars(
    id timeuuid,
    data frozen<car>,
    PRIMARY KEY (id)
);
```

When running INSERT CQL, Notice: Unknown type. in Cassandra\Type\Base.php on line 140 is thrown (which then causes Fatal error: Call to a member function getBinary() on a non-object in Cassandra\Type\CollectionList.php on line 28).

I also tested UDT with a SET<text> and a UDT with a single nested UDT, and these do not cause any issue... thus, I believe this only occurs with a nested set of UDTs (and possibly maps too)

[Edit] A set of UDTs causes the error regardless if nested or not.
[Edit] See my fix in pull request below

**Comment by maliemin-Mstar** [comment]
now, in your example, the `data` field should be write like this:
```
	new Cassandra\Type\UDT
	(
		[
			'make' => 'makeValue',
			'model' => 'modelValue',
			'parts' =>
				[
					['name' => 'name1', 'color' => 'color1'],
					['name' => 'name2', 'color' => 'color2'],
					['name' => 'name3', 'color' => 'color3'],
					['name' => 'name4', 'color' => 'color4'],
				],
		],
		[
			'make' => Cassandra\Type\Base::TEXT,
			'model' => Cassandra\Type\Base::TEXT,
			'parts' =>
				[
					'type' => Cassandra\Type\Base::COLLECTION_SET,
					'value' =>
						[
							'type' => \Cassandra\Type\Base::UDT,
							'typeMap' =>
								[
									'name' => Cassandra\Type\Base::TEXT,
									'color' => Cassandra\Type\Base::TEXT,
								],
						],
				],
		]
	)
```
