### ISSUE TITLE
socket_write result is not checked - partial write is possible

### ISSUE THREAD

**Issue by vovodroid** [duoshuo/php-cassandra#26]
This issue is continue of SSL discussion https://github.com/duoshuo/php-cassandra/pull/20

Currently functions ***(a)syncRequest*** just do ```socket_write($this->connection, $request);``` without test return value, assuming that all data is always sent. This can lead to partial send.

Try following test:
```
$str ='';
for ($i=0;$i<10000000;$i++)	$str .= '#';

$s = socket_create(AF_INET,SOCK_STREAM, SOL_TCP);
socket_set_option($s, SOL_SOCKET, SO_SNDTIMEO, ["sec" => 5, "usec" => 0]);

socket_connect($s,"php.net",80);
//socket_set_nonblock($s);

$sent = socket_write($s,$str);
echo "Sent ".$sent ." bytes\n";
```
If network upload is slow (I set limitation in virtual machine to 28 kbps) socket_write is returns after several seconds and $sent is about 50K. If socket_set_nonblock is uncommented socket_write is returned immediately and only 18K is sent.

The same happens in current php-cassandra code. Connect to remote server with slow connection, make ***syncReqest*** and test socket_write result. It's extreme case, but if you send many long request via slow connection it can happen.

Now no non-blocking mode is used (and can not be used without usage some real async I/O mechanism, like dedicated I/O thread with socket_select) in php-cassandra, but partial send should be handled anyway, something like this:

```
	$reqstr = (string)$request;
	
	while(strlen($reqstr) >0)
	{
		$res = socket_write($this->connection, $reqstr);
		
		if ($res === false)
			throw new Exception(socket_strerror(socket_last_error()));
		
		$reqstr = substr($reqstr,$res);
	}
```

Basing on this I suggest to adopt my SSL addition with above fix. Stream performance is not issue at all.

Thanks.

**Comment by craveica** [comment]
vovodroid is right. Same thing happens if the connection is closed before any data is sent:
Warning: socket_write(): unable to write to socket [104]: Connection reset by peer in vendor/duoshuo/php-cassandra/src/Connection.php on line 242

**Comment by vovodroid** [comment]
----------Same thing happens if the connection is closed before any data is sent
Sure. Connect to C\*, stop in debugger at ***socket_write***, shutdown C\* and continue.

**Comment by shen2** [comment]
Thanks, I've fixed this bug in https://github.com/duoshuo/php-cassandra/commit/07c90e70d2ebc84dda12d5db0c1836be9682828b

**Comment by vovodroid** [comment]
After this commit no exception is thrown on Cassandra error.

Try twice
```
$res = $connection->querySync("CREATE USER test WITH PASSWORD '123'",[]);
$res = $connection->querySync("CREATE USER test WITH PASSWORD '123'",[]);
```
Second $res is  *Cassandra\Response\Error* type

**Comment by vovodroid** [comment]
By a way, queryAsync ... getResponse also don't throw exception.

**Comment by shen2** [comment]
exactly, my fault, I'll fix it immediately

**Comment by vovodroid** [comment]
Here is my solution for queryAsync:
~~~
	public function getResponse(){
		if($this->_response === null){
			$response = $this->_connection->getResponse($this->_streamId);
		}else{
			$response = $this->_response;
		}
		
		if ($response instanceof Response\Error)
			throw new Exception($response->getData());
		
		return $response;
	}
~~~

**Comment by shen2** [comment]
I've merged your pull-request, and add Response\Error check.
