### ISSUE TITLE
fetchData is hanging

### ISSUE THREAD

**Issue by mamdouhweb** [duoshuo/php-cassandra#28]
I tried executing a simple query, but the socket_read is returning an empty string, which makes the remainder - strlen($readData) always equal 9, therefore the while loop is infinite. 

For some reason the socket read is retuning always empty strings. I tested the same query with pdo_cassandra.so extension and it is working, I know it is not a subject of comparison but there is definitely a bug that I can't figure out in the package.

**Comment by shen2** [comment]
Can you tell me the version of you Cassandra?
php-cassandra only support Cassandra 2.1

**Comment by shen2** [comment]
@mamdouhweb Can you tell me the version of your Cassandra?

**Comment by mamdouhweb** [comment]
I have 1.2.
My fault not reading the requirements. However I will submit a pull request
for this issue to throw an error if the reading kept getting empty which
will lead to hang time and infinite loop.

Can you please out of curiosity explain the difference between 2.1 and
older versions from binary protocol perspective on why such an issue might
occur?

Thanks

**Comment by shen2** [comment]
Before 2.0, Cassandra doesn't support binary protocol.
Cassandra 2.0 use protocol v2.
Cassandra 2.1 use protocol v3.

I've no idea how to detect the version of Cassandra.

You may have a try to detect the version.
