### ISSUE TITLE
names_for_values

### ISSUE THREAD

**Issue by arnaud-lb** [duoshuo/php-cassandra#29]
php-cassandra relies on the user for specifying whether the query contains named parameters (rather than positional parameters): If the query option `names_for_values` is not set, names are ignored, and parameters are bound by their position in the array.

The following example results in a user with email and name exchanged in the table, because the parameters are not specified in the same order than in the VALUES clause:

```` php
<?php
$connection->querySync("
    INSERT INTO users (name, email) VALUES (:name, :email)
", array(
    "email" => $email,
    "name" => $name,
));
```

Could php-cassandra just detect that the passed array is associative ?

**Comment by shen2** [comment]
Good advice, let me consider about it.
