### ISSUE TITLE
AuthResponse not handled when user is empty

### ISSUE THREAD

**Issue by vovodroid** [duoshuo/php-cassandra#33]
When connecting to C* with password authentication configured but not providing user/password following message is thrown:
~~~
PHP Fatal error:  Uncaught exception 'Cassandra\Response\Exception' with message 'Server error: java.lang.AssertionError: org.apache.cassandra.exceptions.InvalidRequestException: Key may not be empty' in /root/workspace/cassandra/domain/drivers/php/php-cassandra/src/Response/Error.php:123
~~~

Actually _getResponse gets Frame::OPCODE_AUTHENTICATE, but doesn't handle it.

cqlsh shows
***Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Remote end requires authentication.',)})*** message

**Comment by vovodroid** [comment]
Let close connection in this case:
~~~
			if (empty($nodeOptions['username']) || empty($nodeOptions['password'])){
				$this->_node->close();
				$this->_node = null;
				throw new Exception('Username and password are required.');
			}
~~~
Otherwise connection remains in connected state and will try to send subsequent request anyway.

**Comment by shen2** [comment]
If your code haven't catch this exception, the program will cause fatal error and terminated.
When the program terminated, the connection will be closed automatically.

every exception will cause such situation like this.  We can't closed the connection before every exception.

**Comment by vovodroid** [comment]
This exception is not "every". It's not failed request that doesn't affect next one, but the making the whole session not valid.

**Comment by vovodroid** [comment]
Actually you are right. If user/password not supplied nothing can be done by exit.

I would add separate connect example in readme:
```
$connection = new Cassandra\Connection($nodes);
try
{
	$connection->connect();
}
catch(Exception $e)
{
	echo 'Caught exception: ',  $e->getMessage(), "\n";
	exit;
}
```

**Comment by shen2** [comment]
OK.  That's great.

**Comment by shen2** [comment]
Have a look at my another project "crest".
https://github.com/shen2/crest
Maybe it's useful to you.

**Comment by vovodroid** [comment]
~~~
Slim framework
~~~
I have no idea what it is )))

~~~
That's great.
~~~
Will you update readme?

**Comment by shen2** [comment]
Let me merge your pull-request.
