### ISSUE TITLE
Please provide hints about how to use the Timestamp type

### ISSUE THREAD

**Issue by andreassolberg** [duoshuo/php-cassandra#35]
In the readme, the only example usage of Timestamp is this:

	new Cassandra\Type\Timestamp(1409830696263000);

In my testing, this fails. Fails in a way that makes my cqlsh crash:

	cqlsh:feideconnect> select * from oauth_tokens where access_token = cd9f4f86-0c96-4481-8ca6-abd1df3d2837
	                ... ;
	Traceback (most recent call last):
	  File "/usr/bin/cqlsh", line 960, in perform_simple_statement
	    rows = self.session.execute(statement, trace=self.tracing_enabled)
	  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-2.1.2.zip/cassandra-driver-2.1.2/cassandra/cluster.py", line 1294, in execute
	    result = future.result(timeout)
	  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-2.1.2.zip/cassandra-driver-2.1.2/cassandra/cluster.py", line 2788, in result
	    raise self._final_exception
	ValueError: year is out of range

Reading the code, it seemed to me to be worth an attempt to use:

	new Cassandra\Type\Timestamp(microtime(true));

This did not work properly. I got timestamps like this `1970-01-17 13:14:07+0100`.

Next step then became: 

	new Cassandra\Type\Timestamp(microtime(true)*1000);
	// Similar to 1426447763149.6

This is in fact providing milliseconds (as a float). Doc says microsecond, which would have been `*1000000`.

It is OK to me to work with milliseconds (even if not my first choice), however I am afraid it might change in the future. I also think it is inconsistent with the doc.

**Comment by shen2** [comment]
Actually, the timestamp is in milliseconds. Type of int will be better, not float.
It's defined by Cassandra official document.
The example "new Cassandra\Type\Timestamp(1409830696263000);" is right and tested.

I've updated README.md.  Have a look, and tell me will you be confused.

**Comment by andreassolberg** [comment]
Thanks for the response.

The documentation is clear and consistent about using microseconds.

The problem is that **it is not working for me**. I get the correct behaviour when I feed the timestamp class with milliseconds.

**Comment by shen2** [comment]
@andreassolberg have you tested it again, after today commit?

**Comment by andreassolberg** [comment]
Not today. I'll test and report.

**Comment by andreassolberg** [comment]
If you are thinking about commit e1f1ac8d1c15b1e3f8958c86a38ab1ff69d77732 I believe this only impact initialization of Timestamp objects when using autodetection. Am I right?

In my testing, I have been directly creating new Timestamp objects using the constructor.

I might very well provide a test case running in Travis-CI, however we first need to resolve #37 

The [Datastax documentation on the timestamp data type](http://www.datastax.com/documentation/cql/3.0/cql/cql_reference/timestamp_type_r.html) supports my experience that Cassandra wants to operate with **milliseconds rather than microseconds**.
