### ISSUE TITLE
Check somewhat the Cassandra version

### ISSUE THREAD

**Issue by gonzaloserrano** [duoshuo/php-cassandra#36]
Hi,

It just happend to me that i tried your driver with against Cassandra 2.0.9 and it gets stuck in the inifinite loop here https://github.com/duoshuo/php-cassandra/blob/master/src/Connection/Socket.php#L89 because ```$data``` is something like ```"\n*"Invalid or unsupported protocol version: 3"``` and ```$readData``` is empty string.

I know the README explicetely says that it runs against >= 2.1 but nevertheless i tought this info could be useful to you.

**Comment by shen2** [comment]
Thank you.
I'll try to add version detection.
And I'm welcome to accept pull-request of version detection.

**Comment by shen2** [comment]
I've add version detection in the latest revision.
Have a try. ^_^
