### ISSUE TITLE
Issue with connecting to 127.0.0.1 on Travis CI

### ISSUE THREAD

**Issue by andreassolberg** [duoshuo/php-cassandra#37]
I am very happy with the library so far, but I have a connection issue with Travis-CI where I'm having troubles understanding what is wrong.

### Using sockets

When using `duoshuo` (with sockets) to connect to `127.0.0.1` on Travis-CI, it stalls forever :(

```php
$keyspace = 'feideconnect';
$nodes = ['127.0.0.1'];

echo("connecting to nodes"); 
$db = new \Cassandra\Connection($nodes, $keyspace);

echo "Constructor done\n";
$db->connect();

echo "Connected done\n";
```

It is the `connect()` method that stalls.

### Using stream

As an alternative, I tried with Stream instead of sockets, and instead of stalling/hanging, I get this:

	PHP Fatal error:  Uncaught exception 'Cassandra\Connection\StreamException' with message 'Connection reset by peer' in /home/travis/build/andreassolberg/cassa-test/vendor/duoshuo/php-cassandra/src/Connection/Stream.php:70
	Stack trace:
	#0 /home/travis/build/andreassolberg/cassa-test/vendor/duoshuo/php-cassandra/src/Connection.php(149): Cassandra\Connection\Stream->read(12288)
	#1 /home/travis/build/andreassolberg/cassa-test/vendor/duoshuo/php-cassandra/src/Connection.php(134): Cassandra\Connection->_getResponse()
	#2 /home/travis/build/andreassolberg/cassa-test/vendor/duoshuo/php-cassandra/src/Connection.php(239): Cassandra\Connection->getResponse()
	#3 /home/travis/build/andreassolberg/cassa-test/vendor/duoshuo/php-cassandra/src/Connection.php(211): Cassandra\Connection->syncRequest(Object(Cassandra\Request\Startup))
	#4 /home/travis/build/andreassolberg/cassa-test/bin/duoshuo-stream.php(24): Cassandra\Connection->connect()
	#5 {main}
	  thrown in /home/travis/build/andreassolberg/cassa-test/vendor/duoshuo/php-cassandra/src/Connection/Stream.php on line 70

It is the `feof($this->_stream)` that returns true.

Connection\Stream.php:

```php
		$readData = fread($this->_stream, $length);

		if (feof($this->_stream))
			throw new StreamException('Connection reset by peer');
```

In cases where connection is rejected at port 9042 because no service is listening, the code fails earlier on the `fsockopen()`.

### Using the evseevnn library

For comparison, I earlier used `evseevnn`, which works connecting to the same 127.0.0.1 on Travis CI.

```php
$keyspace = 'feideconnect';
$nodes = ['127.0.0.1'];

echo("connecting to nodes"); 
$db = new \evseevnn\Cassandra\Database($nodes, $keyspace);

echo "Constructor done\n";
$db->connect();
echo "Connected done\n";
```

### Test case running at Travis CI.

I have constructed a dedicated git repo to reconstruct this problem on Travis CI:

* [Source code at github](https://github.com/andreassolberg/cassa-test)
* [Travis CI output that stalls](https://travis-ci.org/andreassolberg/cassa-test)

There is four scripts:

* `bin/duoshuo-socket.php` - Duoshuo with socket **Stalls / hangs**
* `bin/duoshuo-stream.php` - Duoshuo with stream **Throws exception**
* `bin/duoshuo-stream-persistent.php`  - Duoshuo with stream  (persistent).  **Throws exception**
* `bin/evseevnn.php` -  Evseevnn library. **Works OK**

**Any ideas – of how to proceed debugging what is wrong?**

**Comment by shen2** [comment]
I got it.
What's the version your Cassandra? 2.0 or 2.1?
Our library support 2.1 only.

**Comment by andreassolberg** [comment]
Ah, thanks, that might explain it.

Travis-CI only support Cassandra 2.0.x. It is using builds from here: 

* <http://planetcassandra.org/cassandra/>

where 2.0 is the latest stable release, and 2.1 is the development release.

I'll move on to setup a dedicated 2.1 test instance until Travis upgrades..
