### ISSUE TITLE
Cannot submit null value to strictTypeValues()

### ISSUE THREAD

**Issue by steambao** [duoshuo/php-cassandra#38]
When binding, a query with a null valued parameter like this will fail:

```php
$preparedData = $connection->prepare('INSERT INTO user(username, email) VALUES(:username, :email)');

        $strictValues = Request::strictTypeValues(
            [
                'username' => 'jsmith',
                'email' => null,
            ],
            $preparedData['metadata']['columns']
        );

$response = $connection->executeSync(
            $preparedData['id'],
            $strictValues,
            Request::CONSISTENCY_QUORUM,
            [
                'page_size' => 100,
                'names_for_values' => true,
                'skip_metadata' => true,
            ]
        );
```

The error reads:
'Invalid: there were 2 markers(?) in CQL but 1 bound variables' 

This is because public static function strictTypeValues(array $values, array $columns) assigns the index as the key name in $values, rather than the associated name.

I have fixed this issue in my fork, see 7b02cc6f8d5971052d04b50061fa857a2a91ab23

**Comment by shen2** [comment]
thanks, you can send a pull-request, and I will merge it.
