### ISSUE TITLE
Invalid: Expected 8 or 0 byte long for date (24)

### ISSUE THREAD

**Issue by craveica** [duoshuo/php-cassandra#42]
```
Using 'SELECT ... FROM table WHERE ... AND t < minTimeuuid(?)', 
[ 
...
new Cassandra\Type\Varchar('2014-04-01 00:00:00+00000') 
]
```
will fail with message: 
Invalid: Expected 8 or 0 byte long for date (24)

Ref: https://www.datastax.com/documentation/cql/3.0/cql/cql_reference/timeuuid_functions_r.html

**Comment by steambao** [comment]
In the meantime you can convert the ? into a timestamp... this seems to work as a stop-gap solution.

```php
Using 'SELECT ... FROM table WHERE ... AND t < minTimeuuid(?)', 
[ 
...
new Cassandra\Type\Timestamp(strtotime(???)) 
]
```

**Comment by shen2** [comment]
@steambao is right.  You should use Type\Timestamp instead of Type\Varchar

**Comment by craveica** [comment]
new Cassandra\Type\Timestamp(strtotime(???)) did the trick.

Thank you.
