### ISSUE TITLE
Type safety for int / float values

### ISSUE THREAD

**Issue by pako-pl** [duoshuo/php-cassandra#48]
At the moment php-cassandra accepts \Cassandra\Type\Float() for an INT field and \Cassandra\Type\Int() for a FLOAT field. Passing value of the wrong type silently corrupts the data. For example:

- \Cassandra\Type\Float(1.0) inserted to an INT field gives "1065353216"
- \Cassandra\Type\Int(1) inserted to a FLOAT field gives "1.4013e-45"

Is there any way to check the types of the values inserted using the binary protocol?

**Comment by shen2** [comment]
Sorry, the anwser is no.  You should take care of your type by yourself.
