### ISSUE TITLE
How to get data from last inserted row?

### ISSUE THREAD

**Issue by sergeda** [duoshuo/php-cassandra#49]
Trying to insert row with this cql: $cql='INSERT INTO test.posts (uuid, text, title) VALUES (now(), :text, :title)';
Trying to insert this through executeSync and querySync and want to get generated by Cassandra timeUUID by now() function. Is this possible? If not how can this achieved?

**Comment by shen2** [comment]
Cassandra is not mysql, although CQL seems like sql so much.
Try to use timeUUID() first.

**Comment by sergeda** [comment]
Well, I see in database records timeUUID generates by now() function correctly. Here is this function in the docs http://docs.datastax.com/en/cql/3.0/cql/cql_reference/timeuuid_functions_r.html
The only problem - client doesn't return data for row inserted

**Comment by steambao** [comment]
Now() cant be bound. You can let it be plain cql in the string though. But you wont know what has been generated in code (as there is no last insert id). Therefore, best to use a uuid generator in PHP itself, and bind that variable as per normal.

**Comment by sergeda** [comment]
Thank you. Can you please provide an example? In the docs I see this 
new Cassandra\Type\Timeuuid('2dc65ebe-300b-11e4-a23b-ab416c39d509') but where to get this '2dc65ebe-300b-11e4-a23b-ab416c39d509' and will it be generated using current time?

**Comment by steambao** [comment]
So the uuid u generate with a library, such as this https://github.com/ramsey/uuid

You can use whichever library you want. Depending on the library you can generate the uuid based on time or a seed etc...

Then bind the generated uuid string to :uuid as per usual. Sorry I can't post example as in overseas at the moment.

**Comment by sergeda** [comment]
Ok. Thank you. Will try
