### ISSUE TITLE
Call to a member function readOnce() on null

### ISSUE THREAD

**Issue by pako-pl** [duoshuo/php-cassandra#51]
When Cassandra instance stops responding in the middle of a connection, the following PHP error is generated:

    PHP Fatal error: Call to a member function readOnce() on null in /www/vendor/duoshuo/php-cassandra/src/Response/StreamReader.php on line 52

Problematic line:

    $this->data .= $received = $this->source->readOnce($this->totalLength - $this->dataLength);

Is it possible to handle this case by throwing an exception? Something like:

    if($this->source === NULL) {
      throw new CassandraException('The source object is NULL - the connection to Cassandra is broken.');
    }

 Otherwise we can't catch this error and retry the request against a different Cassandra node.

**Comment by vovodroid** [comment]
Hi duoshuo, as I remember we checked this when implemented SSL.

**Comment by shen2** [comment]
@vovodroid not a same problem.

**Comment by 13leaf** [comment]
[native protocol](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v3.spec) 4.2.1 says   
"The body of the message will be an
  error code ([int]) followed by a [string] error message. Then, depending on
  the exception, more content may follow."

It seems like some error parse lost call readString after read error code.
