### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Mshru** [duoshuo/php-cassandra#54]
Hi,
I am new to cassandra. I am trying to set up a connection to cassandra by php.
Although I am assigning username and password, still throws an exception i.e. Username and password required.

**Comment by shen2** [comment]
please show your testing code.

**Comment by Mshru** [comment]
Hi,

Please find the code below,


require 'php-cassandra.php';
$nodes =
    [               // advanced way, array including username, password and
socket options
        'host'      => '---.---.---.---',
        'port'      => 9042, //default 9042
        'username'  => 'remoteuser',
        'password'  => 'cassandra@123',
        'socket'    => [SO_RCVTIMEO => ["sec" => 10, "usec" => 0], //socket
transport only
]
    ];

// Create a connection.
$connection = new Cassandra\Connection($nodes, 'askmesample');

//Connect
try
{
    $connection->connect();
}
catch (Cassandra\Exception $e)
{
    echo 'Caught exception: ',  $e->getMessage(), "\n";
    exit;//if connect failed it may be good idea not to continue
}


// Set consistency level for farther requests (default is CONSISTENCY_ONE)
$connection->setConsistency(Request::CONSISTENCY_QUORUM);

// Run query synchronously.
try
{
    $response = $connection->querySync('SELECT * FROM "users" WHERE "id" =
?', [new Cassandra\Type\Uuid('c5420d81-499e-4c9c-ac0c-fa6ba3ebc2bc')]);
}
catch (Cassandra\Exception $e)
{
}

**Comment by shen2** [comment]
it seems impossible according to your code.
I can't recur this case.  Can you have a try to debug, and I'll merge your pull request.  Thanks.

**Comment by Mshru** [comment]
Thanks.. I resolved it.. It's working fine now
