### ISSUE TITLE
missing file (src/Response/DataStream.php)

### ISSUE THREAD

**Issue by dynamicpacket** [duoshuo/php-cassandra#55]
file required by php-cassandra.php seems to be missing form src/Response.

from php-cassandra.php: 
require 'src/Response/DataStream.php';

**Comment by shen2** [comment]
Thanks. This problem has been solved in https://github.com/duoshuo/php-cassandra/commit/e623d231e0546ee91566f854248f7eccc1e85842

**Comment by dynamicpacket** [comment]
thank you very much :)
