### ISSUE TITLE
About Blob

### ISSUE THREAD

**Issue by muradkarakas** [duoshuo/php-cassandra#57]
Hi All and Shen2

I downloaded this library months ago and have been using it since then. I decided to get new updates. Everything seems working well except blob column values returns NULL.

I realized that getValue function in Type\Blob.php returns NULL since the blob data is in $this->_binary variable not in $this->_value.

ORJINAL FUCNTION which returns NULL:
public function getValue(){
        return $this->_value;
    }

AFTER CHANGING (returns actual blob data):
public function getValue(){
      return $this->_binary;
}

What is wrong here ? Am I wrong ?

Thanks in advance

**Comment by shen2** [comment]
This bug has been fixed in https://github.com/duoshuo/php-cassandra/commit/950f0070d81c80a300eaf4960c41145545ff3e44
Can you have a try and tell me whether it works?
