### ISSUE TITLE
[RFC] Use datastax/php-driver as underlying communication layer

### ISSUE THREAD

**Issue by jippi** [duoshuo/php-cassandra#58]
Hi,

Since DataStax now provide a native PHP extension for Cassandra ( github.com/datastax/php-driver ) - it could be nice if this library either deprecate itself, or start the official client as transport, and act as a compat layer to the new supported extension.

Any thoughts? :)

**Comment by steambao** [comment]
Would be cool, unfortunately Datastax driver still only on v2 binary protocol only

**Comment by shen2** [comment]
It's a good idea.  I'll support Datastax driver when it's ready.

**Comment by jippi** [comment]
I'm using it now, as I don't need custom data classes, and my fairly weak 3 node cluster managed to beat out 110k writes a second - super impressed - never got that kind of speed from the pure php version - looking forward to seeing this library support multiple transports

**Comment by pincher2012** [comment]
https://docs.datastax.com/en/developer/driver-matrix/doc/common/driverMatrix.html

Protocol version 2.1 is supported by php-driver now.
