### ISSUE TITLE
TEXT type return null values

### ISSUE THREAD

**Issue by withings-sas** [duoshuo/php-cassandra#59]
Hello,

Since commit 691c397b213a8c33720dd3c91a4f0e2514bac7d3, a SELECT always returns 'null' value for  TEXT type columns.

**Comment by shen2** [comment]
This bug has been fixed in https://github.com/duoshuo/php-cassandra/commit/950f0070d81c80a300eaf4960c41145545ff3e44
Can you have a try and tell me whether it works?

**Comment by withings-sas** [comment]
Yes it works, thank you :)
