### ISSUE TITLE
PHP7 compatibility - Fatal error: Cannot use 'Int' as class name as it is reserved in duoshuo/php-cassandra/src/Type/Int.php on line 4 

### ISSUE THREAD

**Issue by pako-pl** [duoshuo/php-cassandra#65]
php-cassandra is not compatible with PHP 7:

```Fatal error: Cannot use 'Int' as class name as it is reserved in duoshuo/php-cassandra/src/Type/Int.php on line 4 ```

**Comment by nikhilpnik** [comment]
same for Float PHP Fatal error:  Cannot use 'Float' as class name as it is reserved in /var/www/html/php-cassandra/src/Type/Float.php on line 4

**Comment by pako-pl** [comment]
Thanks. Please also update readme.md. Renaming the types is a potentially breaking change that should be included in the release notes for the next version of the library.
